In [3]:
import netCDF4 as nc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
from keras.layers import Dense, Conv2D, AveragePooling2D, Dropout, BatchNormalization
from keras import optimizers, initializers, callbacks, losses
from keras import Sequential
import os
import sys
from tqdm import tqdm
import pickle
import gc

In [20]:
dataset = nc.Dataset('/Volumes/Yangchao/speckle/Boxcar/Ascending_41001_subset_132_ 4.0_4.0_S1A_IW_GRDH_1SDV_20170629T224915_20170629T224940_017255_01CCB2_E50C')

In [2]:
os.listdir('/Volumes/Yangchao/speckle/')

['Boxcar',
 'Frost',
 'Gamma Map',
 'IDAN',
 'Lee',
 'Lee Sigma',
 'Median',
 'Refined Lee']

In [21]:
dataset.variables.keys()

odict_keys(['Sigma0_VH', 'Sigma0_VV', 'latitude', 'longitude', 'incident_angle', 'elevation_angle', 'slant_range_time', 'lat', 'lon'])

In [22]:
type(sigma_vh)

list

In [28]:
for filter_ in tqdm(os.listdir('/Volumes/Yangchao/speckle/')):
    sigma_vh =[]
    sigma_vv =[]
    incidence = []
    scending = []
    wspeed = []
    wdir = []
    height = []
    sar_data={}
    for file in tqdm(os.listdir('/Volumes/Yangchao/speckle/'+filter_)):
        dataset = nc.Dataset('/Volumes/Yangchao/speckle/'+filter_+'/'+file)
        if dataset.variables['Sigma0_VH'][:].shape!=(400, 400):
            dataset.close()
            del dataset
            gc.collect()
            continue
        
        sigma_vh.append(dataset.variables['Sigma0_VH'][:])
        sigma_vv.append(dataset.variables['Sigma0_VV'][:])
        incidence.append(dataset.variables['incident_angle'][:])
        file_list = file.split('_')
        scending.append(file_list[0])
        wdir.append(int(file_list[3]))
        wspeed.append(float(file_list[4]))
        height.append(float(file_list[5]))
        dataset.close()
        del dataset
        gc.collect()
        
#     with open('/Volumes/Yangchao/sigma_vv'+'_'+filter_, 'wb') as v:
#         pickle.dump(sigma_vv, v)
#     with open('/Volumes/Yangchao/sigma_vh'+'_'+filter_, 'wb') as h:
#         pickle.dump(sigma_vh, h)
#     with open('/Volumes/Yangchao/incidence'+'_'+filter_, 'wb') as i:
#         pickle.dump(incidence, i)


    datas = pd.DataFrame({'wspeed':wspeed, 'wdir':wdir, 'height':height, 'scending':scending})
    datas.to_csv('/Volumes/Yangchao/'+filter_, index=False)
    sar_data['sigma_vv']=sigma_vv
    sar_data['sigma_vh']=sigma_vh
    sar_data['incidence']=incidence
    with open('/Volumes/Yangchao/sar_'+filter_, 'wb') as ss:
        pickle.dump(sar_data, ss)
    gc.collect()



 81%|████████  | 215/265 [00:22<00:05,  9.70it/s]


 59%|█████▉    | 157/265 [00:16<00:11,  9.53it/s]


 30%|███       | 80/265 [00:08<00:19,  9.61it/s]


 93%|█████████▎| 247/265 [00:26<00:01,  9.37it/s]


 57%|█████▋    | 152/265 [00:16<00:12,  9.27it/s]


 22%|██▏       | 59/265 [00:06<00:22,  9.23it/s]


 90%|█████████ | 239/265 [00:25<00:02,  9.32it/s]


 11%|█         | 28/265 [00:03<00:26,  8.94it/s]/Users/yangchao/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:12: RuntimeWarning: invalid value encountered in less
/Users/yangchao/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:18: RuntimeWarning: invalid value encountered in less

 51%|█████     | 134/265 [00:14<00:13,  9.36it/s]


 54%|█████▎    | 142/265 [00:15<00:13,  9.38it/s]/Users/yangchao/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:19: RuntimeWarning: invalid value encountered in less

 18%|█▊        | 47/265 [00:05<00:23,  9.14it/s]


 83%|████████▎ | 220/265 [00:23<00:04,  9.20it/s]


 46%|████▌     | 122/265 [00:12<00:15,  9.42it/s]


100%|██████████| 8/8 [04:27<00:00, 33.46s/it]


In [36]:
with open('/Volumes/Yangchao/filter/sar_IDAN', 'rb') as f:
    sar_IDAN= pickle.load(f)

In [37]:
len(sar_IDAN['sigma_vh'])

258

In [19]:
x.shape== (2, 2)

True

In [13]:
sigma_vv_IDAN

{'incidence': [], 'sigma_vh': [], 'sigma_vv': []}

In [6]:
import pickle

In [84]:
from sklearn import preprocessing

In [85]:
normalizer = preprocessing.Normalizer('max')

In [152]:
sigma_vv_new =[]
for data in tqdm(files):
    new = normalizer.fit_transform(data)
    sigma_vv_new.append(new)

100%|██████████| 2120/2120 [00:00<00:00, 2243.06it/s]


In [21]:
sigma_vv_new[0]

array([[0.4222096 , 0.27688953, 0.07447106, ..., 0.11735603, 0.09671693,
        0.11737202],
       [0.24697523, 0.36790574, 0.30949277, ..., 0.16576958, 0.11864164,
        0.11865129],
       [0.3655567 , 0.42587715, 0.530799  , ..., 0.3383197 , 0.338336  ,
        0.26352105],
       ...,
       [0.0583945 , 0.03735812, 0.21079934, ..., 0.35504028, 0.26110289,
        0.23017283],
       [0.11880817, 0.06104958, 0.1839634 , ..., 0.26541108, 0.1945616 ,
        0.20796697],
       [0.22756967, 0.24652508, 0.576889  , ..., 0.18002544, 0.23356313,
        0.35753208]], dtype=float32)

In [22]:
sigma_vv[0]

array([[0.01988052, 0.01303786, 0.00350661, ..., 0.00552593, 0.0045541 ,
        0.00552668],
       [0.00899812, 0.01340402, 0.01127584, ..., 0.00603953, 0.00432251,
        0.00432286],
       [0.01027171, 0.01196665, 0.01491483, ..., 0.00950639, 0.00950684,
        0.00740463],
       ...,
       [0.00249261, 0.00159466, 0.00899811, ..., 0.01515513, 0.01114535,
        0.00982508],
       [0.00561291, 0.00288419, 0.00869107, ..., 0.01253893, 0.00919176,
        0.00982508],
       [0.00666817, 0.00722359, 0.0169038 , ..., 0.00527504, 0.00684379,
        0.01047628]], dtype=float32)

In [158]:
model = Sequential()

In [159]:
model.add(AveragePooling2D((2,2),strides=2, input_shape=(256,256,1)))

In [160]:
model.add(Conv2D(32, (3,3),activation='relu',kernel_initializer=initializers.he_normal()))

In [161]:
model.add(AveragePooling2D((2,2), strides=2))

In [162]:
model.add(BatchNormalization())

In [163]:
model.add(Dropout(0.3))

In [164]:
model.add(Conv2D(64, (3,3), activation='relu', kernel_initializer=initializers.he_normal()))

In [165]:
model.add(AveragePooling2D((2,2),strides=2))

In [166]:
model.add(BatchNormalization())

In [167]:
model.add(Dropout(0.3))

In [168]:
model.add(Conv2D(128, (3,3), activation='relu', kernel_initializer=initializers.he_normal()))

In [169]:
model.add(AveragePooling2D((2,2),strides=2))
model.add(BatchNormalization())
model.add(Dropout(0.3))

In [170]:
model.add(Conv2D(256, (3,3), activation='relu', kernel_initializer=initializers.he_normal()))
model.add(AveragePooling2D((2,2),strides=2))
model.add(BatchNormalization())
model.add(Dropout(0.3))

In [53]:
model.add(Conv2D(256, (3,3), activation='relu', kernel_initializer=initializers.he_normal()))
model.add(AveragePooling2D((2,2),strides=2))
model.add(BatchNormalization())
model.add(Dropout(0.3))

In [171]:
model.add(keras.layers.Flatten())

In [172]:
model.add(Dense(36, activation='sigmoid', kernel_initializer=initializers.he_normal()))

In [173]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
average_pooling2d_15 (Averag (None, 128, 128, 1)       0         
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 126, 126, 32)      320       
_________________________________________________________________
average_pooling2d_16 (Averag (None, 63, 63, 32)        0         
_________________________________________________________________
batch_normalization_10 (Batc (None, 63, 63, 32)        128       
_________________________________________________________________
dropout_10 (Dropout)         (None, 63, 63, 32)        0         
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 61, 61, 64)        18496     
_________________________________________________________________
average_pooling2d_17 (Averag (None, 30, 30, 64)        0         
__________

In [57]:
from PIL import Image

In [65]:
image =Image.fromarray(sigma_vv[0])

In [150]:
files = []
labels = []
scend = []
for i, array in enumerate(sigma_vv):
    print(array.shape)
    images= []
    wdirs = []
    asc = []
    image = Image.fromarray(array)
    w = 256
    h = 256
    x0=0
    y0=0
    dx = 5
    dy = 5
    while x0<40:
        while y0<40:
            im = image.crop((y0, x0, w, h))
            a = np.array(im)
            print(a.shape)
            images.append(a)
            wdirs.append(wdir[i])
            asc.append(scending[i])
            w +=dx
            h +=dx
            x0+=dx
            y0+=dy
    files.extend(images)
    labels.extend(wdirs)
    scend.extend(asc)

(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)

(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)

(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(400, 400)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)

In [151]:
print(np.array(files).shape)

(2120, 256, 256)


In [148]:
f[0,0].shape

(256, 256)

In [90]:
files = np.array(files)

In [92]:
files[:10]

array([array([[0.01988052, 0.01303786, 0.00350661, ..., 0.01040586, 0.01282288,
        0.00975757],
       [0.00899812, 0.01340402, 0.01127584, ..., 0.01625841, 0.01355446,
        0.01107445],
       [0.01027171, 0.01196665, 0.01491483, ..., 0.01585833, 0.00975707,
        0.01211011],
       ...,
       [0.01491281, 0.01569584, 0.01303778, ..., 0.00598151, 0.00404322,
        0.00651274],
       [0.01267492, 0.01196595, 0.01267615, ..., 0.00881634, 0.00382146,
        0.00547021],
       [0.01127397, 0.00838844, 0.00931009, ..., 0.01790381, 0.01175915,
        0.0067848 ]], dtype=float32),
       array([[0.00839122, 0.00561677, 0.00751197, ..., 0.00762816, 0.01210957,
        0.01546404],
       [0.01690697, 0.01377787, 0.01340774, ..., 0.00881696, 0.01875556,
        0.01790575],
       [0.01649983, 0.01491742, 0.01267986, ..., 0.00762816, 0.01430432,
        0.0146867 ],
       ...,
       [0.01415187, 0.01093855, 0.00536407, ..., 0.00598151, 0.00404322,
        0.00651274],
     

In [93]:
labels[:10]

[132, 132, 132, 132, 132, 132, 132, 132, 201, 201]

In [94]:
scend[:10]

['Ascending',
 'Ascending',
 'Ascending',
 'Ascending',
 'Ascending',
 'Ascending',
 'Ascending',
 'Ascending',
 'Ascending',
 'Ascending']

In [97]:
delta = []
for x in scend:
    if x=='Ascending':
        y=80
    else:
        y=280
    delta.append(y)

In [99]:
labels= np.array(labels)
delta = np.array(delta)
l = (labels-delta)%360

In [100]:
l[:10]

array([ 52,  52,  52,  52,  52,  52,  52,  52, 121, 121])

In [121]:
ll = l//10*10

In [122]:
ll[:10]

array([ 50,  50,  50,  50,  50,  50,  50,  50, 120, 120])

In [103]:
ll[100]

55

In [123]:
onehot = preprocessing.OneHotEncoder()

In [124]:
ll.transpose().shape

(2120,)

In [125]:
label = onehot.fit_transform(ll.reshape((2120,1)))

In [126]:
label.shape

(2120, 36)

<1x72 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [127]:
normal = preprocessing.Normalizer()

In [174]:
model.compile(loss=losses.categorical_crossentropy, metrics=[keras.metrics.categorical_accuracy], optimizer=optimizers.RMSprop(lr=0.0004))

In [181]:
earlystop = callbacks.EarlyStopping(verbose=10)

In [176]:
tb = callbacks.TensorBoard('./log')

In [155]:
sigma_vv_new = np.array(sigma_vv_new)
svn = sigma_vv_new.reshape((2120,256,256, 1))

In [156]:
svn.shape

(2120, 256, 256, 1)

In [143]:
for s in sigma_vv_new:
    print(s.shape)
    X.append(s.reshape((256, 256, 1)))

(256, 256)
(251, 251)


ValueError: cannot reshape array of size 63001 into shape (256,256,1)

In [182]:
model.fit(svn, label, callbacks=[earlystop, tb], batch_size=32, epochs=32, shuffle=True, validation_split=0.3)

Train on 1484 samples, validate on 636 samples
Epoch 1/32
1484/1484 [==============================] - 73s 49ms/step - loss: 1.0686 - categorical_accuracy: 0.7588 - val_loss: 6.0619 - val_categorical_accuracy: 0.0267
Epoch 2/32
1484/1484 [==============================] - 73s 49ms/step - loss: 0.8242 - categorical_accuracy: 0.8181 - val_loss: 6.1108 - val_categorical_accuracy: 0.0314
Epoch 00002: early stopping


In [180]:
svn[0]

array([[[0.4222096 ],
        [0.27688953],
        [0.07447106],
        ...,
        [0.22099282],
        [0.27232388],
        [0.20722488]],

       [[0.24697523],
        [0.36790574],
        [0.30949277],
        ...,
        [0.44625148],
        [0.37203488],
        [0.30396494]],

       [[0.3655567 ],
        [0.42587715],
        [0.530799  ],
        ...,
        [0.5643771 ],
        [0.34724134],
        [0.4309829 ]],

       ...,

       [[0.4748752 ],
        [0.49980947],
        [0.41516784],
        ...,
        [0.19047181],
        [0.12875007],
        [0.20738818]],

       [[0.4171774 ],
        [0.39384255],
        [0.4172179 ],
        ...,
        [0.2901775 ],
        [0.12577792],
        [0.18004435]],

       [[0.37772316],
        [0.2810465 ],
        [0.31192532],
        ...,
        [0.5998494 ],
        [0.39397874],
        [0.22731811]]], dtype=float32)